services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - open-webui_data:/app/backend/data
    environment:
      - 'PIPELINES_URL=http://pipelines:9099'
      - 'MCP_URL=http://mcpo:9553'
    networks:
      - webui-network
    restart: always
    depends_on:
      - pipelines
      - mcpo

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"
    volumes:
      - ./pipes:/app/pipelines
    networks:
      - webui-network
    restart: always

  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: mcpo
    ports:
      - "8000:8000"
    volumes:
      - ./mcp.json:/app/config.json
    command: mcpo --config /app/config.json --host 0.0.0.0
    networks:
      - webui-network

volumes:
  open-webui_data:

networks:
  webui-network:
    driver: bridge
